# Generated by Django 5.0.2 on 2024-09-13 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoCap_server", "0002_videocapconfig_redis_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currentframe",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Frame",
                "verbose_name_plural": "Frames",
            },
        ),
        migrations.AlterField(
            model_name="currentframe",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frames",
                to="videoCap_server.videocapconfig",
            ),
        ),
        migrations.AlterField(
            model_name="currentframe",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
