# Generated by Django 5.0.2 on 2024-09-18 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "videoCap_server",
            "0003_alter_currentframe_options_alter_currentframe_config_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentVideoClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clip_path", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_clips",
                        to="videoCap_server.videocapconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Clip",
                "verbose_name_plural": "Video Clips",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AIInferenceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "video_clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_results",
                        to="videoCap_server.currentvideoclip",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Inference Result",
                "verbose_name_plural": "AI Inference Results",
                "ordering": ["-timestamp"],
            },
        ),
    ]
