# Generated by Django 5.0.2 on 2024-10-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCap_server', '0004_currentvideoclip_aiinferenceresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_url', models.CharField(max_length=255)),
            ],
        ),
    ]
