# Generated by Django 5.0.2 on 2024-10-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCap_server', '0005_cameralist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameralist',
            options={'verbose_name': '攝像頭', 'verbose_name_plural': '攝像頭列表'},
        ),
        migrations.AlterField(
            model_name='cameralist',
            name='camera_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cameralist',
            name='camera_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
