# Generated by Django 5.0.2 on 2024-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCap_server', '0006_alter_cameralist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameralist',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Camera List'},
        ),
        migrations.AddField(
            model_name='cameralist',
            name='camera_status',
            field=models.BooleanField(default=False),
        ),
    ]
