# Generated by Django 5.0.2 on 2024-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCap_server', '0007_alter_cameralist_options_cameralist_camera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralist',
            name='stream_upload_video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
