# Generated by Django 5.0.2 on 2024-11-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoCap_server', '0008_cameralist_stream_upload_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameralist',
            name='camera_status',
        ),
        migrations.RemoveField(
            model_name='cameralist',
            name='stream_upload_video_path',
        ),
    ]
