# Generated by Django 5.0.2 on 2024-09-04 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                ("scan_frequency", models.IntegerField()),
                ("aggregation_interval", models.IntegerField()),
                ("violation_threshold", models.FloatField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntityType",
            fields=[
                ("entity_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KeyFrame",
            fields=[
                ("frame_id", models.AutoField(primary_key=True, serialize=False)),
                ("frame_time", models.DateTimeField()),
                ("frame_index", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("rule_id", models.AutoField(primary_key=True, serialize=False)),
                ("rule_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("severity_level", models.IntegerField()),
                ("condition_logic", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SceneType",
            fields=[
                ("scene_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DetectedObject",
            fields=[
                (
                    "detected_object_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("specific_type", models.CharField(max_length=100)),
                ("confidence_score", models.FloatField()),
                ("bounding_box", models.JSONField()),
                ("segmentation", models.JSONField()),
                ("re_id", models.IntegerField()),
                (
                    "parent_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visionAI_server.detectedobject",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visionAI_server.entitytype",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visionAI_server.keyframe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonRole",
            fields=[
                ("person_role_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "detected_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visionAI_server.detectedobject",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visionAI_server.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                ("scene_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visionAI_server.keyframe",
                    ),
                ),
                (
                    "scene_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visionAI_server.scenetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                ("violation_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "occurrence_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "detected_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visionAI_server.detectedobject",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visionAI_server.keyframe",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visionAI_server.rule",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visionAI_server.scene",
                    ),
                ),
            ],
        ),
    ]
