# Generated by Django 5.0.2 on 2024-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visionAI_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionAIConfig",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                ("violation_detect_frequency", models.IntegerField(default=1)),
                ("aggregation_interval", models.IntegerField(default=5)),
                ("violation_threshold", models.FloatField(default=0.5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Config",
        ),
    ]
