# Generated by Django 5.0.2 on 2024-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visionAI_server", "0004_alter_detectedobject_entity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyframe",
            name="rtmp_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
