# Generated by Django 5.0.2 on 2024-11-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionAI_server', '0005_keyframe_rtmp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDrawingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_url', models.URLField(unique=True)),
                ('is_drawing', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '攝影機畫圖狀態',
                'verbose_name_plural': '攝影機畫圖狀態',
            },
        ),
    ]
