# Generated by Django 5.0.2 on 2024-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SRSServerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(
                        default="registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4",
                        max_length=255,
                    ),
                ),
                (
                    "container_name",
                    models.CharField(default="srs_server", max_length=100),
                ),
                ("rtmp_port", models.IntegerField(default=1935)),
                ("http_api_port", models.IntegerField(default=1985)),
                ("http_server_port", models.IntegerField(default=8080)),
                (
                    "config_file",
                    models.CharField(default="conf/docker.conf", max_length=100),
                ),
            ],
            options={
                "verbose_name": "SRS Server Configuration",
                "verbose_name_plural": "SRS Server Configurations",
            },
        ),
    ]
