# Generated by Django 5.0.2 on 2024-09-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srsserverconfig',
            name='container_name',
            field=models.CharField(default='srs_container', max_length=100),
        ),
        migrations.AlterField(
            model_name='srsserverconfig',
            name='docker_image',
            field=models.CharField(default='ossrs/srs:5', max_length=255),
        ),
    ]
